version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - '9092:9092'
      - '9999:9999'
      - '29092:29092'
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    depends_on:
      - kafka-zookeeper
  kafka-zookeeper:
        image: confluentinc/cp-zookeeper:7.2.1
        ports:
          - '2181:2181'
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_SERVERS: kafka-zookeeper:2888:3888
  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      networks:
        - broker-kafka
      depends_on:
        - kafka
      ports:
        - "19000:9000"
      environment:
        KAFKA_BROKERCONNECT: kafka:29092
  mongodb:
      image: mongo:latest
      env_file:
        - .env
      ports:
        - "27017:27017"
      networks:
        - broker-kafka
      volumes:
        - mongodb_data_container:/data/db
  kafka-consumer:
      build: ./kafka-consumer
      container_name: kafka-consumer
      depends_on:
        - mongodb
        - kafka
      networks:
        - broker-kafka
      ports:
        - "3000:3000"
        - "9229:9229"
      command: npm run start:prod
  kafka-producer:
      build: ./kafka-producer
      container_name: kafka-producer
      env_file:
        - kafka-producer/.env
      depends_on:
        - kafka
      networks:
        - broker-kafka
      ports:
        - "3001:3001"
networks:
  broker-kafka:
    driver: bridge

volumes:
  mongodb_data_container: